services:
  engine:
    image: "voicevox/voicevox_engine:cpu-ubuntu20.04"
    build: 
      context: voicevox_engine
      target: runtime-env
      args:
        - VOICEVOX_CORE_ASSET_PREFIX=voicevox_core-linux-arm64-cpu
    restart: unless-stopped
    environment:
      VV_CPU_NUM_THREADS: 4
    volumes:
      - "./data:/home/user/.local/share/voicevox-engine-dev/"
  node:
    build: .
    depends_on:
      - engine
    restart: unless-stopped
    volumes:
      - "./:/app"
    working_dir: "/app"
    ports:
      - "50021:3000"
    command: "yarn start"
