services:
  engine:
    image: "voicevox/voicevox_engine:cpu-latest"
    restart: unless-stopped
    environment:
      VV_CPU_NUM_THREADS: 4
    volumes:
      - "./data:/home/user/.local/share/voicevox-engine-dev/"
    healthcheck:
      test: ["CMD", "wget", "--post-data=", "localhost:50021/audio_query?text=test&speaker=3", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 10

  node:
    build: Docker/node
    depends_on:
      engine:
        condition: service_healthy
      client:
        condition: service_completed_successfully
    restart: unless-stopped
    volumes:
      - "./:/app"
    working_dir: "/app"
    ports:
      - "50021:3000"
    command: "yarn start"
    healthcheck:
      test: ["CMD", "wget", "localhost:3000/speak?text=test", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 10

  client:
    build: Docker/client
    volumes:
      - "./:/app"
    working_dir: "/app/client"
    command: sh ../client_init.sh